### ISSUE TITLE
Drop support for old PHP versions

### ISSUE THREAD

**Issue by NicolasCARPi** [fastsitephp/fastsitephp#11]
Hello,

I see that you are still supporting PHP 5.3 !!

My advice is to drop the support for such old versions and move the codebase forward by integrating new PHP features like type hinting. In 2020 there is no need to support less than 7.2.

It is the developer's role to push users to upgrade their PHP version to keep the web secure! ;)

Also, you're missing out on a ton of modern PHP features that are REALLY useful, if you choose to stick with old versions.

You can't put "security" as a keyword for your app if it runs on PHP 5.3 :p .

Static analysis tools could also help you a lot. For instance, the property `$status_code` of `Web/Response` is declared as `string|null`, but then you assign an `int` to it at multiple places, that's not good!

![2020-01-22-224809_1277x1019_scrot](https://user-images.githubusercontent.com/3043706/72937364-495e5200-3d69-11ea-9a03-a8058c11a9ca.png)

Cheers,
~Nico

**Comment by ConradSollitt** [comment]
Hello Nico!

Thanks so much for opening this issue and running a static analysis tools against FastSitePHP. I made a few fixed on the PHPDoc Comments based on your print screen and I've updated the readme file warning against old PHP.

I gave you credit in the change-log as well based on your helpful issue:
https://github.com/fastsitephp/fastsitephp/blob/master/CHANGELOG.md

**Question 1** What static analysis tools are you using or do you recommend and which one did you use for the print screen?

Basically I have a lot of Unit Testing Code that runs to verify all key parts of the Framework (more Unit Testing code than Framework code actually) however I currently don't validate PHPDoc Comments which is clear as I had at least 2 mistakes in the Response class. My goal is have Unit Testing for every single line of code but that is a long term goal and will take a lot of time, currently all major code for how routing works, security features, etc are carefully tested.

**Question 2** Take a look at the bottom of the main readme file related to supported PHP versions. Anything else you would recommend adding? If so feel free to add it or simply comment here and I can add it.

In regards to old version of PHP I see WordPress is still supporting `5.6.20` as of today. They had planned on dropping PHP5 support by the end of last year but looks like they haven't been able to yet. Historically WordPress had to support really old versions of PHP because a lot of web hosts still run them.

https://wordpress.org/about/requirements/

https://wordpress.org/news/2019/04/minimum-php-version-update/

Also related to this is how to actually handle old version of PHP in corporate environments. Not really a question to answer but more of an issue to ponder. Old software takes a long time to get upgraded at many companies (assuming they are not public facing web severs). My plans for this are to recommend old releases of FastSitePHP only if someone can't upgrade and then support that latest widely used versions of PHP. For an extreme example you can see print screens of PHP (with the Database class) running on very old IBM servers:

https://www.fastsitephp.com/en/documents/ibm-server-db-query

**Comment by ConradSollitt** [comment]
Related to old versions of PHP I just came across this link. Somewhat amusing if anyone has time to read or scan it.

One user mentioned that Red Hat will support PHP 5.6 until 2024 but I can't find an actual link myself supporting that claim.

https://www.reddit.com/r/PHP/comments/esc41i/can_one_of_you_guys_find_a_vulnerability_bad/

**Comment by NicolasCARPi** [comment]
1: I used [psalm](https://github.com/vimeo/psalm). Get the .phar from the releases page and add it in your $PATH (with the .asc).

~~~bash
psalm --init
psalm
~~~

I also recommend using [phpstan](https://github.com/phpstan/phpstan).

As for Unit testing, it looks like you are using custom code, right? I highly recommend using the now very standard `phpunit` or something like `codeception`. Having a testing framework is a must. Note that I was not able to find out how to run the tests!

2: do you really have companies relying on your code? It's totally fine to release a 2.x.x version that breaks compatibility with old PHP versions, that's what semver is for. The incentive here is also for the software itself, nowadays, a PHP project that doesn't use strict typing will surely have many more bugs than one that does. But you can't do that if you don't use PHP7.

Don't take Wordpress as an example. The wordpress codebase is a big mess and they are used by a tremendous amount of users, so they don't have the liberty that you have.

I'm aware that companies take a long time to update stuff, but if developers enable them by having low version requirements, it won't improve the situation and the company will lose $$ when they get hacked because they use vulnerable software. Please read this article: https://kinsta.com/blog/php-versions/.

Regards,
~Nico

**Comment by ConradSollitt** [comment]
Thanks Nico!

(1) Great link and help with `psalm` setup. `psalm` is working great and I've starting fixing the the issues - almost all are related to the PHPDoc comments such as functions not including `@return void`. Years ago I used the JetBrains PhpStorm IDE for this but at some point it became a lot more forgiving for false-positives from PHPDoc comments by default so I stopped limiting with it.

I'll continue updating them till all issues are resolved (hopefully within a week or two). If anyone reading this would like to help out feel free. More detailed instructions are near the top of the to-do-list file: https://github.com/fastsitephp/fastsitephp/blob/master/docs/to-do-list.txt

(2) In regards to usage. I wouldn't expect many at this point although I have a lot of other priorities at the moment rather than refactoring to remove PHP 5. So it will happen in the future, just not right now. On the earlier reddit post I shared I see that someone now posted a link showing that CentOS will support PHP 5.3 till November of 2020 and in fact RedHat does indeed support PHP 5.4 until June of 2024. Basically the enterprise Linux vendors are back-filling security fixes for their paying customers - I was actually wondering about this recently because RedHat still installed PHP 5.4 by default (I tested it just last month to see if it still installed 5.4 by default). As you mentioned `semver` it's what FastSitePHP uses so if needed I can refer someone to the `1.*` release once PHP 5 is dropped.

Related to PHP versions - even though FastSitePHP works with PHP 5.3 it actively targests new features. For example the Password class supports `argon2` and Encryption class unit tests with `sha3-512` if using `PHP 7.2+`.

In regards to Unit Testing I would also like to add CLI testing with `phpunit` or something in the future but at the moment Unit Testing is done through a Web Browser. I'm aware that it's a very unusual method of testing server side code but it has worked very well for developing FastSitePHP.

I found that it was faster for workflow during development and that it makes it easy to test the Framework in any Environment (rather than just testing known Server Variables). An example of this is regarding 304 caching responses with etags. Basically there are two types of etags (strong and weak) and in mock environments they would always work however I found that recently strong etags were not working with nginx but they still worked with Apache and IIS. After some quick searches I found the cause is that nginx (with good reason) assumes strong etags are a developer error and converts them to weak etags. If FastSitePHP uses only CLI testing with mock environments I would have had a hard time figuring it out.

I plan on creating a proper document in the near future describing how the unit testing works in more detail but in the meantime the main test code is located in this folder: https://github.com/fastsitephp/fastsitephp/tree/master/tests

Example URL's if running locally:
`http://localhost:3000/fastsitephp/tests/index.htm` or `http://localhost:3000/tests/index.htm`

Here are two print screens as well. One showing the success result when all tested Unit Tests pass and the other showing specific warnings if a server won't support certain features such as PUT or DELETE requests.

![FastSitePHP Unit Testing Success](https://raw.githubusercontent.com/fastsitephp/static-files/master/img/screenshots/fastsitephp-unit-testing-success.png)

![FastSitePHP Unit Testing Warning](https://raw.githubusercontent.com/fastsitephp/static-files/master/img/screenshots/fastsitephp-unit-testing-warning.png)

Thanks again for this issue as it will help with linting which helps the code base. Plus now the readme at least has better warnings not to use old PHP.

Regards,
Conrad

**Comment by NicolasCARPi** [comment]
Another thing you might want to use is php_cs (see [example config](https://github.com/elabftw/elabftw/blob/master/.php_cs.dist)). It helps with stuff like useless `use` statements and other crap that is not worthy of spending time on but it's nice to have if it's automatically done like reorganizing the public/protected/private functions in a class and stuff like that.

For the tests, if you have something that works for you, it's fine, at least you have tests! :)

One thing that you might be missing, is CI. For instance, on each commit I do on elabftw/elabftw, there is a CircleCI job that will test things and let me know if they fail, this is pretty useful. It also does it for PRs. Example: https://circleci.com/gh/elabftw/elabftw/4746 (it also runs linters that will trigger an error if it's not perfect).

Good luck with fixing all the errors and warnings from the static analysis! ;)

~Nico

**Comment by ConradSollitt** [comment]
Thanks for the tips Nico!

Yeah CI is something I'm planning for the future but haven't made it a priority just yet. So far I've tested and have been using `phpstan, psalm, and phan`. The vast majority of the errors have been related to PHPDoc comments or false positives that I have unit tests for. For JavaScript I typically validate all my scripts with both `eslint` and `'jshint`.

I haven't yet decided if I'll keep using all 3 or just stick with one. So far I like `phpstan` a lot with my current code base. The reason being that you can specify levels 0 to 8 of error checking so it allows you to keep focused on what it considers the priority rather than seeing everything at once. So far I'm up to level 4. It's tedious but goes pretty quick.

Yeah I agree with having tests. It's probably been the most important part of development as I would keep adding tests for all key code during development as I wrote it.

I've been thinking a lot about the issue that you first raised (dropping support for old PHP) and will continue giving it a lot of thought (and more research) over the next few weeks. One eye opener for me is that some of the major Linux vendors are supporting old PHP 5 until 2029 so in reality while it is not recommended by the PHP Group or most PHP developers it is widely used. I just checked server stats (link below) and it shows that PHP 5 is still more widely used than PHP7 .

One of my goals with FastSitePHP was to make it work with as many environments as possible rather than being focused on just a few and to make it as accessible as possible (I’m working with translators to have it translated). So in the near future at least I’ll likely be testing with more versions of Linux, adding more support for FreeBSD, etc, rather than dropping PHP 5 support. But as I mentioned I’ll be giving this topic  a lot of thought over the next few weeks and doing further research.

https://w3techs.com/technologies/details/pl-php

~Conrad
