### ISSUE TITLE
Question: How does this compare against Laravel?

### ISSUE THREAD

**Issue by SuperlativeEntity** [fastsitephp/fastsitephp#2]
I'm currently using Laravel. Other than performance, what does this framework offer that is better? Bearing in mind that if I do need raw performance, I can use Lumen.

**Comment by ConradSollitt** [comment]
Great Question

For raw performance FastSitePHP is typically 2 to 6 times faster for a minimal app and the performance gap is even better for complex apps. That was one of the key reasons why I wrote FastSitePHP in the first place, that and I felt that the developer experience when using most PHP Frameworks is very poor compared to frameworks in other popular languages. That said Luman is still very fast and the difference is unlikely to be noticed by end users for most sites under normal traffic loads.

In fact, for dynamic sites that need the highest level of performance (example a real-time multiplayer game with a lot of traffic) you would probably want to develop with another language entirely (Java, Go, Node). For example, a [case study from AWS shows that Supercell](https://aws.amazon.com/solutions/case-studies/supercell/) (mobile game maker) uses Java to process 45 billion events per day. Facebook originally used PHP but then for improved performance they modified it into a spate language called [Hack Lang](https://hacklang.org/).

Personally I would recommend PHP Developers to learn both Laravel and Symfony enough that they can include them on their resume. However the world is a lot different now than it was 5-10 years ago so the bigger challenge is for PHP to stay relevant. Basically node/express generally has better performance than PHP is the first server framework that new developers typically learn on and since Python is great for Data Science flask is ideal for a lot of apps. To address the issue of why someone should learn PHP I include a few points in the readme of this repository.

I myself use many different frameworks and recommend other developers do the same to keep up with trends and stay relevant. In fact my other large GitHub project [DataFormsJS](https://github.com/dataformsjs/dataformsjs) uses 3 frameworks and languages on the main site: [PHP with FastSitePHP, node/JavaScript/express for GraphQL, and python/flask for AI/ML services with TensorFlow and scikit-learn.

## Here are some reasons to use FastSitePHP aside from overall performance

* **Easy to work with and learn**
  * [Online Playground](https://www.fastsitephp.com/en/playground) on the main site allows developers to learn both PHP and the Framework for free without having to install anything.
  * Well documented - [Quick Reference Page](https://www.fastsitephp.com/en/quick-reference) on Site, examples, API docs, and more make it easy to quickly find what you need
  * Very flexible for development, by design FastSitePHP is a minimal Framework that has a lot of built-in components. Major PHP Frameworks typically borrow ideas from Java or .NET which can make them bloated as it’s arguably not appropriate for PHP while FastSitePHP uses an un-opinionated design and is closer to node/express or Python/flask for development.
  * Small Size - Lumen needs over 5,200+ files (24+ mb) to use while FastSitePHP needs only small files. The full FastSite framework and Starter site are less than 500 files (mostly small JSON files for l10n).
  * [FastSitePHP is extremely easy to install](https://www.fastsitephp.com/en/getting-started) (only 2 shell commands needed for a full Linux Ubuntu server setup). The main site and framework run without having to install anything other than PHP using the GitHub download link and the main FastSitePHP website provides step by step instructions for Linux, Windows, and Mac users.
* **Easy to use for Data Apps**
  * Database Classes for PDO, ODBC, and IBM DB2/AS400
  * SMTP Client and Email Support - High Performance and minimal in size. Includes SMTP logging ability for easy debugging of SMTP issues.
  * Easy to use Data Validation
  * High performance DotEnv port based on most widely used node/JavaScript version
  * File System Tools for Searching and Syncing
  * Networking - Easy to work with class and functions for working with IP Addresses and CIDR Strings (often important for security)
  * System Info with wide OS support: (Linux, Mac, Windows, FreeBSD, IBM)
  * Encoding
    * Base64 URL’s (not included with PHP by default)
    * JSON (BigInt Support for older versions of PHP)
    * UTF8 for Array’s -needed for JSON Services if a server or database isn’t using UTF8 by default
* **Strong support for Multilingual Sites**
  * Simple Internationalization (I18N) API - works with JSON and Text Files and does not require a complex setup
  * Easy to use Localization (l10n) API (formatting of date, time, and numbers)
* **Focus on Security**
  * File System Security - Working with user input for file paths, reading images, etc
  * JSON Web Tokens (JWT)
  * Easy to use Data Encryption [string, int, float, bool, array, object, and null]. Advanced Encryption Standard (AES) with Block Modes CBC, CTR, GCM, and CCM are all supported and fully tested. Data Encryption is useful for Cookies, and Web Data.
  * File Encryption - high performance and works with huge files (100+ gb), compatible bash script
  * Generic Signed Data Format.  Just like Encryption this is use for Cookies, Authentication and other Web Data
  * CSRF (both Session and Stateless). Stateless CSRF are not common however are very useful - [in fact PayPal uses them with Node/JavaScript](https://medium.com/paypal-engineering/securing-your-js-apps-w-stateless-csrf-9a60ee6bd010)
  * Easy to use Password Class for Security Password Storage
  * Rate Limiting, example usage
    * A Web API allowing users to submit no more than 1 request every second.
    * No more than 2 new accounts per day per IP address.
    * Limit users from sending more than 10 messages per hour.
* **PHP Support**
  * Works with all versions of PHP from 5.3 to 7.3
  * FastSitePHP runs fast even on very old PHP 5.3 servers

## Performance Comparison with Larvel/Lumen

For this comparison AWS Lightsail is used with Linux Ubuntu 18.04 LTS, SSD, 1 GB of memory and 1 vCPU. FastSitePHP can be installed on the smaller 512 mb of memory server, however Lumen requires at least 1 GB otherwise composer will not work.

<p align="center">
	<img src="https://fastsitephp.s3-us-west-1.amazonaws.com/img/github-comments/fastsitephp-vs-laravel-lumen/aws-instance-os.png" alt="AWS Lightsail Instance OS">
</p>
<p align="center">
	<img src="https://fastsitephp.s3-us-west-1.amazonaws.com/img/github-comments/fastsitephp-vs-laravel-lumen/aws-instance-size.png" alt="AWS Lightsail Instance Size">
</p>

FastSitePHP Starter Site Install
~~~bash
# The bash script [create-fastsitephp-app.sh] automatically installs everything
# needed [Apache, PHP, etc], and performs setup, permissions, and other tasks.
wget https://www.fastsitephp.com/downloads/create-fastsitephp-app.sh
sudo bash create-fastsitephp-app.sh
# View site by IP (public IP will be displayed in terminal).
~~~

Laravel Lumen Starter Site Basic Install
~~~bash
# Install Apache, PHP, etc
sudo apt update
sudo apt install -y apache2 unzip php libapache2-mod-php php7.2-zip php7.2-pdo php7.2-xml php7.2-mbstring

# Setup Fallback Resource of [/index.php] for Apache
sudo sed -i '/<Directory \/var\/www\/>/a \\tFallbackResource \/index.php' /etc/apache2/apache2.conf
sudo service apache2 restart

# Install Composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

# Set permissions and create a Lumen project in the default [~] directory
sudo adduser ubuntu www-data
sudo chown ubuntu:www-data -R /var/www
sudo chmod 0775 -R /var/www
php composer.phar create-project laravel/lumen blog "5.1.*"

# Copy needed files and delete the default Apache page
cp -r ~/blog/app /var/www/app
cp -r ~/blog/bootstrap /var/www/bootstrap
cp -r ~/blog/database /var/www/database
cp -r ~/blog/public/. /var/www/html
cp -r ~/blog/resources /var/www/resources
cp -r ~/blog/storage /var/www/storage
cp -r ~/blog/vendor /var/www/vendor
sudo rm /var/www/html/index.html

# View site by IP
~~~

AWS provides a browser based terminal so a server can be setup using the above commands from any computer with internet access once you create an AWS account. Note, the IP addresses shown below were for a temporary server that has now been deleted.

<p align="center">
	<img src="https://fastsitephp.s3-us-west-1.amazonaws.com/img/github-comments/fastsitephp-vs-laravel-lumen/create-app-start.png" alt="Create FastSitePHP App">
</p>
<p align="center">
	<img src="https://fastsitephp.s3-us-west-1.amazonaws.com/img/github-comments/fastsitephp-vs-laravel-lumen/create-app-end.png" alt="Create FastSitePHP App Complete">
</p>

For a raw performance comparison of speed and memory on a single request the following steps can be used.

**FastSitePHP Server**
~~~bash
# Add [?_debug=stats] to the end of any URL and view the page
# Example:
#     http://{server}/en/?_debug=stats

# Example Output:
# Script Time: 0.00032806396484375
# Starting Memory Usage: 376.578125 KB
# Ending Memory Usage: 404.3671875 KB
# Peak Memory Usage: 424.3984375 KB
~~~

**Laravel/Lumen Server**
~~~bash
cd /var/www/html
wget https://raw.githubusercontent.com/fastsitephp/fastsitephp/master/src/Utilities/debug.php
nano index.php
# Add to the 2nd line of the file:
#	require __DIR__ . '/debug.php';
# Add as the last line in the file:
#	$showDebugInfo();

# Example Output:
# Script Time: 0.00067901611328125
# Starting Memory Usage: 375.75 KB
# Ending Memory Usage: 667.109375 KB
# Peak Memory Usage: 679.09375 KB
~~~

The above example shows that FastSitePHP was twice as fast and used 38% less memory, however the speed for both is very fast the difference is so tiny that no user would notice the difference on a single page view.

The reason for this is simply because Laravel needs to load 40 classes for a hello world example while FastSitePHP is loading only 3, this can be shown by adding the following to bottom of each [index.php] file:
~~~php
$all_classes = array_values(get_declared_classes());
$all_classes = array_filter($all_classes, function($class) {
    return (strpos($class, '\\') !== false);
});
echo 'Classes Used: ' . count($all_classes);
echo '<br>';
echo implode('<br>', $all_classes);
~~~

However we need a more real-world test than a single page view so for that we are going to use Apache Benchmark to make 10,000 total requests using 100 concurrent users. First make, if you added `$showDebugInfo();` or the above classes code to the Laravel Server make sure to comment it out.

~~~bash
# Install
sudo apt install apache2-utils

# Then run tests:

# For the Laravel Server
ab -n 10000 -c 100 http://localhost/

# For the FastSitePHP Server
ab -n 10000 -c 100 http://localhost/en/
~~~

Requests per second for FastSitePHP are typically around 3500 to 6500 while Laravel Lumen supports around 1100 to 2200 for the tested servers.

<p align="center">
	<img src="https://fastsitephp.s3-us-west-1.amazonaws.com/img/github-comments/fastsitephp-vs-laravel-lumen/ab-fastsitephp.png" alt="Apache Benchmark with FastSitePHP">
</p>
<p align="center">
	<img src="https://fastsitephp.s3-us-west-1.amazonaws.com/img/github-comments/fastsitephp-vs-laravel-lumen/ab-laravel-lumen.png" alt="Apache Benchmark with Laravel Lumen">
</p>

## Summary

For raw performance FastSitePHP is typically 2 to 6 times faster than Larvel Lumen but the difference is unlikely to be noticed by end users for most sites under normal traffic loads.

The earlier list provides reasons why you would want to use FastSitePHP for development and for why you would want to learn PHP in the first place see the [README](https://github.com/fastsitephp/fastsitephp) of this repository.

Additionally most of the classes for FastSitePHP are plain PHP classes and do not require FastSitePHP so you can use them with your existing apps and favorite PHP frameworks such as Symfony, Laravel, Zend, Slim, and more.

If you haven't already tried FastSitePHP try it in out in one second with one button click using the Code Playground:

https://www.fastsitephp.com/en/playground

**Comment by ConradSollitt** [comment]
Latest update after a Benchmark Comparison:

FastSitePHP scored the fastest of all PHP Frameworks using a standard nginx setup. 

* 19.6 times faster than Laravel
* 3.5 times faster than Symfony

https://github.com/the-benchmarker/web-frameworks

There are other faster PHP frameworks but all depend on swoole or other custom servers that require service reboot when PHP files change.

**Comment by SuperlativeEntity** [comment]
Thanks, but I'll stick with Laravel purely because of the quality of life features and their ecosystem.

My original question excluded performance.

"Other than performance, what does this framework offer that is better?"

**Comment by ConradSollitt** [comment]
Sure, I just wanted to provide a performance update here.

I wouldn't really say one framework is better than another in general but rather use the right framework/tool for the job needed. In fact the main site for expressjs doesn't event use express and instead uses GitHub pages (Ruby/Jekyll) so that is a good example of a popular framework using other technology for it's site.

Laravel does have a huge ecosystem and is one of the most popular frameworks from all languages so it's a good choice for many developers and good for the resume.

Quite possibly most important (at least for a lot of people) is to pick a language that pays well in the area you live. When I started writing the original code FastSitePHP back in 2013/2014 PHP was a well paid language in Los Angeles (where I live), however in general selecting other languages (and non-PHP frameworks) pays much more.

Because of this I most commonly work with Python, Node, and DotNet for Server Side code. However I do consider PHP to be very useful due to it's flexibility and ability to simply update individual files without having to restart services on a server. WordPress is good examples of this because you can fully update the sever code with only a browser. In the future I plan on creating CMS based on FastSitepPHP but will do it as I have time or when I create more real-world sites from it.

As for using FastSitePHP the points I listed in my original response are what I would recommend it for. Basically FastSitePHP is good if you want a lot of flexibility for programming (similar to using node/express or python/flask) compared to the Laravel which is highly structured and has a lot of API's. Additionally FastSitePHP is well suited for sites with high security needs as it has a lot of security features built in without the need for third-party code and it's designed to be very easy to use so developers from other languages can get started right away without having to know much PHP.
